{
  "description": "findOne-serverErrors",
  "schemaVersion": "1.9",
  "runOnRequirements": [
    {
      "minServerVersion": "4.0",
      "topologies": [
        "single",
        "replicaset"
      ]
    },
    {
      "minServerVersion": "4.1.7",
      "topologies": [
        "sharded",
        "load-balanced"
      ]
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "useMultipleMongoses": false,
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "retryable-reads-tests"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "coll"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "coll",
      "databaseName": "retryable-reads-tests",
      "documents": [
        {
          "_id": 1,
          "x": 11
        },
        {
          "_id": 2,
          "x": 22
        },
        {
          "_id": 3,
          "x": 33
        },
        {
          "_id": 4,
          "x": 44
        },
        {
          "_id": 5,
          "x": 55
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "FindOne succeeds after InterruptedAtShutdown",
      "operations": [
        {
          "object": "testRunner",
          "name": "failPoint",
          "arguments": {
            "client": "client0",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "find"
                ],
                "errorCode": 11600
              }
            }
          }
        },
        {
          "object": "collection0",
          "name": "findOne",
          "arguments": {
            "filter": {
              "_id": 1
            }
          },
          "expectResult": {
            "_id": 1,
            "x": 11
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "FindOne succeeds after InterruptedDueToReplStateChange",
      "operations": [
        {
          "object": "testRunner",
          "name": "failPoint",
          "arguments": {
            "client": "client0",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "find"
                ],
                "errorCode": 11602
              }
            }
          }
        },
        {
          "object": "collection0",
          "name": "findOne",
          "arguments": {
            "filter": {
              "_id": 1
            }
          },
          "expectResult": {
            "_id": 1,
            "x": 11
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "FindOne succeeds after NotWritablePrimary",
      "operations": [
        {
          "object": "testRunner",
          "name": "failPoint",
          "arguments": {
            "client": "client0",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "find"
                ],
                "errorCode": 10107
              }
            }
          }
        },
        {
          "object": "collection0",
          "name": "findOne",
          "arguments": {
            "filter": {
              "_id": 1
            }
          },
          "expectResult": {
            "_id": 1,
            "x": 11
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "FindOne succeeds after NotPrimaryNoSecondaryOk",
      "operations": [
        {
          "object": "testRunner",
          "name": "failPoint",
          "arguments": {
            "client": "client0",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "find"
                ],
                "errorCode": 13435
              }
            }
          }
        },
        {
          "object": "collection0",
          "name": "findOne",
          "arguments": {
            "filter": {
              "_id": 1
            }
          },
          "expectResult": {
            "_id": 1,
            "x": 11
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "FindOne succeeds after NotPrimaryOrSecondary",
      "operations": [
        {
          "object": "testRunner",
          "name": "failPoint",
          "arguments": {
            "client": "client0",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "find"
                ],
                "errorCode": 13436
              }
            }
          }
        },
        {
          "object": "collection0",
          "name": "findOne",
          "arguments": {
            "filter": {
              "_id": 1
            }
          },
          "expectResult": {
            "_id": 1,
            "x": 11
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "FindOne succeeds after PrimarySteppedDown",
      "operations": [
        {
          "object": "testRunner",
          "name": "failPoint",
          "arguments": {
            "client": "client0",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "find"
                ],
                "errorCode": 189
              }
            }
          }
        },
        {
          "object": "collection0",
          "name": "findOne",
          "arguments": {
            "filter": {
              "_id": 1
            }
          },
          "expectResult": {
            "_id": 1,
            "x": 11
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "FindOne succeeds after ShutdownInProgress",
      "operations": [
        {
          "object": "testRunner",
          "name": "failPoint",
          "arguments": {
            "client": "client0",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "find"
                ],
                "errorCode": 91
              }
            }
          }
        },
        {
          "object": "collection0",
          "name": "findOne",
          "arguments": {
            "filter": {
              "_id": 1
            }
          },
          "expectResult": {
            "_id": 1,
            "x": 11
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "FindOne succeeds after HostNotFound",
      "operations": [
        {
          "object": "testRunner",
          "name": "failPoint",
          "arguments": {
            "client": "client0",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "find"
                ],
                "errorCode": 7
              }
            }
          }
        },
        {
          "object": "collection0",
          "name": "findOne",
          "arguments": {
            "filter": {
              "_id": 1
            }
          },
          "expectResult": {
            "_id": 1,
            "x": 11
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "FindOne succeeds after HostUnreachable",
      "operations": [
        {
          "object": "testRunner",
          "name": "failPoint",
          "arguments": {
            "client": "client0",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "find"
                ],
                "errorCode": 6
              }
            }
          }
        },
        {
          "object": "collection0",
          "name": "findOne",
          "arguments": {
            "filter": {
              "_id": 1
            }
          },
          "expectResult": {
            "_id": 1,
            "x": 11
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "FindOne succeeds after NetworkTimeout",
      "operations": [
        {
          "object": "testRunner",
          "name": "failPoint",
          "arguments": {
            "client": "client0",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "find"
                ],
                "errorCode": 89
              }
            }
          }
        },
        {
          "object": "collection0",
          "name": "findOne",
          "arguments": {
            "filter": {
              "_id": 1
            }
          },
          "expectResult": {
            "_id": 1,
            "x": 11
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "FindOne succeeds after SocketException",
      "operations": [
        {
          "object": "testRunner",
          "name": "failPoint",
          "arguments": {
            "client": "client0",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "find"
                ],
                "errorCode": 9001
              }
            }
          }
        },
        {
          "object": "collection0",
          "name": "findOne",
          "arguments": {
            "filter": {
              "_id": 1
            }
          },
          "expectResult": {
            "_id": 1,
            "x": 11
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "FindOne fails after two NotWritablePrimary errors",
      "operations": [
        {
          "object": "testRunner",
          "name": "failPoint",
          "arguments": {
            "client": "client0",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 2
              },
              "data": {
                "failCommands": [
                  "find"
                ],
                "errorCode": 10107
              }
            }
          }
        },
        {
          "object": "collection0",
          "name": "findOne",
          "arguments": {
            "filter": {
              "_id": 1
            }
          },
          "expectError": {
            "isError": true
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "FindOne fails after NotWritablePrimary when retryReads is false",
      "operations": [
        {
          "object": "testRunner",
          "name": "createEntities",
          "arguments": {
            "entities": [
              {
                "client": {
                  "id": "client1",
                  "useMultipleMongoses": false,
                  "uriOptions": {
                    "retryReads": false
                  },
                  "observeEvents": [
                    "commandStartedEvent"
                  ]
                }
              },
              {
                "database": {
                  "id": "database1",
                  "client": "client1",
                  "databaseName": "retryable-reads-tests"
                }
              },
              {
                "collection": {
                  "id": "collection1",
                  "database": "database1",
                  "collectionName": "coll"
                }
              }
            ]
          }
        },
        {
          "object": "testRunner",
          "name": "failPoint",
          "arguments": {
            "client": "client1",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "find"
                ],
                "errorCode": 10107
              }
            }
          }
        },
        {
          "object": "collection1",
          "name": "findOne",
          "arguments": {
            "filter": {
              "_id": 1
            }
          },
          "expectError": {
            "isError": true
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client1",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll",
                  "filter": {
                    "_id": 1
                  }
                },
                "databaseName": "retryable-reads-tests"
              }
            }
          ]
        }
      ]
    }
  ]
}
