runOn:
    -
        minServerVersion: "4.0"
        topology: ["replicaset"]
    -
        minServerVersion: "4.1.7"
        topology: ["sharded"]

data:
    - { _id: 1, x: 11 }
    - { _id: 2, x: 22 }

tests:
    -
        description: "ReplaceOne succeeds after PrimarySteppedDown"
        failPoint:
            configureFailPoint: failCommand
            mode: { times: 1 }
            data:
                failCommands: ["update"]
                errorCode: 189
                errorLabels: ["RetryableWriteError"]
        operation:
            name: "replaceOne"
            arguments:
                filter: { _id: 1 }
                replacement: { _id: 1, x: 111 }
        outcome:
            result:
                matchedCount: 1
                modifiedCount: 1
                upsertedCount: 0
            collection:
                data:
                    - { _id: 1, x: 111 }
                    - { _id: 2, x: 22 }
    -
        description: "ReplaceOne succeeds after WriteConcernError ShutdownInProgress"
        failPoint:
            configureFailPoint: failCommand
            mode: { times: 1 }
            data:
                failCommands: ["update"]
                writeConcernError:
                    code: 91
                    errmsg: Replication is being shut down
                    errorLabels: ["RetryableWriteError"]
        operation:
            name: "replaceOne"
            arguments:
                filter: { _id: 1 }
                replacement: { _id: 1, x: 111 }
        outcome:
            result:
                matchedCount: 1
                modifiedCount: 1
                upsertedCount: 0
            collection:
                data:
                    - { _id: 1, x: 111 }
                    - { _id: 2, x: 22 }
    -
        description: "ReplaceOne fails with a RetryableWriteError label after two connection failures"
        failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
                failCommands: ["update"]
                closeConnection: true
        operation:
            name: "replaceOne"
            arguments:
                filter: { _id: 1 }
                replacement: { _id: 1, x: 111 }
        outcome:
            error: true
            result:
                errorLabelsContain: ["RetryableWriteError"]
            collection:
                data:
                    - { _id: 1, x: 11 }
                    - { _id: 2, x: 22 }
